version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: .docker/backend.dockerfile
    command: bash -c "npm run build && npm run production"
    volumes:
      - .:/usr/poc-chef/
      - /usr/poc-chef/node_modules
    ports:
      - "3000:3000"
